export const ErrorCodes = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_001',
  AUTH_TOKEN_EXPIRED: 'AUTH_002',
  AUTH_TOKEN_INVALID: 'AUTH_003',
  AUTH_OTP_INVALID: 'AUTH_004',
  AUTH_OTP_EXPIRED: 'AUTH_005',
  AUTH_ACCOUNT_LOCKED: 'AUTH_006',
  AUTH_PHONE_NOT_VERIFIED: 'AUTH_007',

  // Identity
  IDENTITY_NOT_FOUND: 'IDENTITY_001',
  IDENTITY_ALREADY_EXISTS: 'IDENTITY_002',
  IDENTITY_VERIFICATION_PENDING: 'IDENTITY_003',
  IDENTITY_BIOMETRIC_REQUIRED: 'IDENTITY_004',

  // Financial
  FINANCIAL_INSUFFICIENT_FUNDS: 'FIN_001',
  FINANCIAL_TRANSFER_FAILED: 'FIN_002',
  FINANCIAL_INVALID_AMOUNT: 'FIN_003',
  FINANCIAL_HOLD_ACTIVE: 'FIN_004',
  FINANCIAL_DISPUTE_OPEN: 'FIN_005',
  FINANCIAL_PAYOUT_LIMIT_EXCEEDED: 'FIN_006',

  // Mobility
  MOBILITY_NO_DRIVERS_AVAILABLE: 'MOB_001',
  MOBILITY_RIDE_NOT_FOUND: 'MOB_002',
  MOBILITY_RIDE_ALREADY_ACTIVE: 'MOB_003',
  MOBILITY_ZONE_UNAVAILABLE: 'MOB_004',

  // Governance
  GOV_POLICY_VIOLATION: 'GOV_001',
  GOV_COMPLIANCE_REQUIRED: 'GOV_002',
  GOV_PROHIBITED_SCOPE: 'GOV_003',

  // Trust/Safety
  TRUST_LOW_SCORE: 'TRUST_001',
  TRUST_FRAUD_DETECTED: 'TRUST_002',
  TRUST_MANUAL_REVIEW_REQUIRED: 'TRUST_003',

  // Payout
  PAYOUT_PENDING: 'PAY_001',
  PAYOUT_FAILED: 'PAY_002',
  PAYOUT_LIMIT_EXCEEDED: 'PAY_003',
  PAYOUT_METHOD_INVALID: 'PAY_004',

  // Generic
  NOT_FOUND: 'GEN_001',
  VALIDATION_ERROR: 'GEN_002',
  RATE_LIMIT_EXCEEDED: 'GEN_003',
  INTERNAL_ERROR: 'GEN_004',
  SERVICE_UNAVAILABLE: 'GEN_005',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
